version: "3.7"

services:
  app:
    image: my_app
    ports:
      - 3000:3000
    environment:
      MYSQL_HOST: mysql
      MYSQL_USER: root
      MYSQL_PASSWORD: mysecret
      MYSQL_DB: todos

  mysql:
    image: mysql:5.7
    volumes:
      - /c/Users/reyqs/Dev/Docker/volumes/:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: mysecret
      MYSQL_DATABASE: todos